"""Render the three empirical figures from released data and model coordinates.

The normal entry reads resource_descriptive.parquet and coordinates generated by
the analysis runner. The explicit --from-reference option only redraws saved
coordinates, for inspection of the plotting implementation.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import inspect
import json
import sys
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
from PIL import Image


HERE = Path(__file__).resolve().parent


def _module(name: str, filename: Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, filename)
    if spec is None or spec.loader is None:
        raise ImportError(filename.name)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


evolution_style = _module("figure_evolution_style", HERE / "evolution_style.py")
alignment_tool = _module("figure_alignment_tool", HERE / "qa_tools/audit_panel_alignment.py")
font_tool = _module("figure_font_tool", HERE / "qa_tools/audit_pdf_text.py")
collision_tool = _module("figure_collision_tool", HERE / "qa_tools/audit_figure_collisions.py")


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")


def _style() -> None:
    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans", "sans-serif"],
        "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 7,
        "xtick.labelsize": 6, "ytick.labelsize": 6, "legend.fontsize": 6,
        "axes.spines.right": False, "axes.spines.top": False, "axes.linewidth": .7,
        "text.color": "black", "axes.labelcolor": "black", "axes.titlecolor": "black",
        "axes.edgecolor": "black", "xtick.color": "black", "ytick.color": "black",
        "pdf.fonttype": 42, "svg.fonttype": "none", "savefig.facecolor": "white",
        "svg.hashsalt": "scientific-impact-figures",
    })


def _label(axis: Any, label: str) -> None:
    axis.text(-.18, 1.08, label, transform=axis.transAxes, fontsize=8,
              fontweight="bold", va="top", ha="left")


def _save(fig: Any, axes: list[Any], stem: Path, *, evolution: bool = False, inset: Any = None) -> dict:
    """Measure the final geometry, export editable formats and audit the PDF."""
    stem.parent.mkdir(parents=True, exist_ok=True)
    qa = stem.parent / "qa"
    qa.mkdir(parents=True, exist_ok=True)
    fig.canvas.draw()
    options: dict = {"axes": axes, "panel_ids": [chr(97 + i) for i in range(len(axes))]}
    if evolution:
        options["row_groups"] = [{"id": "gpu-hardware-row", "panels": ["a", "b", "c"], "orientation": "row"}]
    alignment = alignment_tool.require_matplotlib_panel_alignment(
        fig, json_out=qa / f"{stem.name}.alignment.json",
        overlay_svg=qa / f"{stem.name}.alignment.svg", tolerance_pt=1.5,
        gutter_tolerance_pt=1.5, require_panel_labels=True, strict=True, **options,
    )
    save_options = {} if evolution else {"bbox_inches": "tight"}
    fig.savefig(stem.with_suffix(".pdf"), metadata={"Creator": "Offline replication package", "CreationDate": None,
                "ModDate": None, "Title": stem.name}, **save_options)
    fig.savefig(stem.with_suffix(".svg"), metadata={"Title": stem.name, "Date": None}, **save_options)
    fig.savefig(stem.with_suffix(".png"), dpi=600, metadata={"Software": "Offline replication package"}, **save_options)
    plt.close(fig)
    pdf_path = stem.with_suffix(".pdf")
    fonts = font_tool.audit_pdf(pdf_path.read_bytes(), minimum_pt=5)
    collisions = collision_tool.audit_pdf(pdf_path)
    collisions["pdf"] = pdf_path.name
    _write_json(qa / f"{stem.name}.fonts.json", fonts)
    _write_json(qa / f"{stem.name}.collisions.json", collisions)
    if not fonts.get("auditable") or fonts.get("below_minimum_count", 0):
        raise ValueError(f"PDF font audit failed: {stem.name}")
    if not collisions.get("auditable") or collisions.get("summary", {}).get("fail", 0):
        raise ValueError(f"PDF collision audit failed: {stem.name}")
    if inset is not None:
        _write_json(qa / f"{stem.name}.inset.json", {"role": "Auxiliary API-configuration zoom",
                    "alignment_exclusion": True, "reason": "Intentional zoom with a different height and scale"})
    return {"alignment": alignment.get("verdict"), "font_minimum_pt": 5,
            "font_minimum_found_pt": fonts.get("minimum_found_pt"),
            "font_text_runs": fonts.get("text_run_count", 0),
            "font_below_minimum_count": fonts.get("below_minimum_count", 0),
            "font_auditable": fonts.get("auditable", False),
            "collision_auditable": collisions.get("auditable", False),
            "collision_failures": collisions.get("summary", {}).get("fail", 0),
            "collision_warnings": collisions.get("summary", {}).get("warn", 0),
            "formats": [f"figures/{stem.name}.{ext}" for ext in ("png", "pdf", "svg")]}


def _guard_coordinates(frame: pd.DataFrame, x: str, center: str, low: str, high: str) -> None:
    values = frame[[x, center, low, high]].to_numpy(dtype=float)
    if not np.isfinite(values).all():
        raise ValueError("Figure coordinates contain missing or infinite values")
    if not (frame[low].le(frame[center]) & frame[center].le(frame[high])).all():
        raise ValueError("Figure confidence limits do not contain the estimate")
    if not np.all(np.diff(frame[x].to_numpy(dtype=float)) > 0):
        raise ValueError("Figure coordinates must have distinct increasing x values")


def aggregate_evolution(frame: pd.DataFrame, config: dict) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """Annual counts and linear quantiles, with the original population rules."""
    gpu = config["component_configs"]["gpu_hardware"]
    access = config["component_configs"]["hardware_api"]
    columns = gpu["columns"]
    required = set(columns.values()) | set(access["columns"].values()) | {v["column"] for v in gpu["variables"]}
    missing = required.difference(frame.columns)
    if missing:
        raise ValueError(f"Missing evolution fields: {sorted(missing)}")
    if frame["paper_id"].isna().any() or frame["paper_id"].duplicated().any():
        raise ValueError("Evolution paper_id must be non-null and unique")
    if len(frame) != 107872 or frame["year"].isna().any() or not frame["year"].between(2020, 2025).all():
        raise ValueError("Evolution input must contain the 107872 eligible papers from 2020 through 2025")
    flags = ["resource_L1", "resource_L2", "resource_L3", "resource_L4", "compute_gpu_scale_strict_main_sample",
             "compute_strict_gpu", "compute_performance_imputed"]
    for flag in flags:
        if frame[flag].isna().any() or not frame[flag].isin([0, 1, False, True]).all():
            raise ValueError(f"Nonbinary evolution flag: {flag}")
    hardware = frame["resource_L1"].eq(1) & frame["resource_L2"].eq(0) & frame["resource_L3"].eq(0)
    api = frame["resource_L4"].eq(1)
    measurement = hardware & frame[columns["current_complete"]].eq(True)
    variable_columns = [v["column"] for v in gpu["variables"]]
    positive = frame[variable_columns].notna().all(axis=1) & frame[variable_columns].gt(0).all(axis=1)
    if not measurement.equals(hardware & positive):
        raise ValueError("Complete GPU flag differs from the same-configuration positive-field intersection")
    imputed = measurement & frame[columns["performance_imputed"]].eq(True)
    totals = {"input_n": len(frame), "hardware_n": int(hardware.sum()), "measurement_n": int(measurement.sum()),
              "api_n": int(api.sum()), "performance_imputed_n": int(imputed.sum())}
    expected = {"input_n": 107872, "hardware_n": 49090, "measurement_n": 34483,
                "api_n": 20633, "performance_imputed_n": 3524}
    if totals != expected:
        raise ValueError(f"Evolution population mismatch: {totals}")
    masks = {"hardware_only": hardware & ~api, "hardware_api": hardware & api,
             "api_only": ~hardware & api, "neither_identified": ~hardware & ~api}
    access_rows, gpu_rows = [], []
    for year in range(2020, 2026):
        in_year = frame["year"].eq(year)
        denominator = int(in_year.sum())
        if denominator != access["expected"]["annual"][str(year) if str(year) in access["expected"]["annual"] else year]["denominator"]:
            raise ValueError(f"Year {year} denominator differs from the reference contract")
        for order, state in enumerate(access["configurations"], start=1):
            count = int((in_year & masks[state["id"]]).sum())
            access_rows.append({"year": year, "configuration": state["id"], "display_name": state["display_name"],
                                "stack_order": order, "paper_count": count, "year_denominator": denominator,
                                "paper_share": count / denominator})
        sample = in_year & measurement
        for variable in gpu["variables"]:
            values = pd.to_numeric(frame.loc[sample, variable["column"]], errors="raise") / float(variable["divisor"])
            if not np.isfinite(values).all() or not values.gt(0).all():
                raise ValueError("Hardware quantiles require finite positive measurements")
            q = values.quantile([.25, .5, .75, .9], interpolation="linear")
            gpu_rows.append({"year": year, "variable": variable["id"], "display_name": variable["display_name"],
                             "unit": variable["unit"], "provenance_cohort_n": int((in_year & hardware).sum()),
                             "measurement_n": int(sample.sum()), "q25": float(q.loc[.25]), "median": float(q.loc[.5]),
                             "q75": float(q.loc[.75]), "p90": float(q.loc[.9])})
    return pd.DataFrame(access_rows), pd.DataFrame(gpu_rows), totals


def draw_api(predictions: pd.DataFrame, contrasts: pd.DataFrame, output_dir: Path) -> dict:
    _style()
    if len(predictions) != 606 or len(contrasts) != 3:
        raise ValueError("API figure expects 606 coordinates and 3 interaction contrasts")
    colors, styles = {0: "#4477AA", 1: "#EE7733"}, {0: "-", 1: "--"}
    titles = {"quantity": "GPU Quantity × API", "performance": "Per-GPU Performance × API", "memory": "Per-GPU VRAM × API"}
    fig, arr = plt.subplots(1, 3, figsize=(7.2, 2.65), sharey=True, squeeze=False)
    axes = list(arr.flat)
    contrast_index = contrasts.set_index("hardware")
    for i, hardware in enumerate(("quantity", "performance", "memory")):
        axis = axes[i]
        axis.axhline(0, color="#A0A0A0", linewidth=.6, zorder=0)
        axis.axvline(0, color="#D0D0D0", linewidth=.6, zorder=0)
        for api in (0, 1):
            part = predictions.loc[predictions["hardware"].eq(hardware) & predictions["api"].eq(api)].sort_values("doublings_from_full_v14_median")
            if len(part) != 101:
                raise ValueError("Each API/hardware curve must contain 101 coordinates")
            _guard_coordinates(part, "doublings_from_full_v14_median", "adjusted_change", "ci_low", "ci_high")
            x = part["doublings_from_full_v14_median"].to_numpy(float)
            axis.fill_between(x, part["ci_low"].to_numpy(float), part["ci_high"].to_numpy(float), color=colors[api], alpha=.12, linewidth=0)
            axis.plot(x, part["adjusted_change"].to_numpy(float), color=colors[api], linestyle=styles[api], linewidth=1.35)
        axis.set_title(titles[hardware] + f"\nInteraction $p$ = {float(contrast_index.loc[hardware, 'interaction_p_value']):.3f}",
                       fontsize=7.2, fontweight="bold", pad=4)
        if i == 0:
            axis.set_ylabel("Cumulative Citations\n(outcome-SD change)")
        _label(axis, chr(97 + i))
    handles = [Line2D([0], [0], color=colors[v], linestyle=styles[v], label=["No API", "API"][v]) for v in (0, 1)]
    fig.legend(handles=handles, loc="upper center", ncol=2, frameon=False, bbox_to_anchor=(.5, .995))
    fig.supxlabel("Hardware capability (doublings relative to sample median)", fontsize=7, y=.035)
    fig.subplots_adjust(left=.12, right=.985, top=.78, bottom=.22, wspace=.24)
    return _save(fig, axes, output_dir / "figures/interaction_slopes_cumulative_citations")


def draw_ksc(grid: pd.DataFrame, output_dir: Path) -> dict:
    _style()
    if len(grid) != 404:
        raise ValueError("KSC figure expects four panels of 101 coordinates")
    titles = {"a": "GPU quantity – cumulative citations", "b": "GPU quantity – top-cited 10%",
              "c": "GPU quantity – top-cited 5%", "d": "API access – top-cited 1%"}
    ylabels = {"a": "Association per doubling\n(% change in 1 + citations)",
               "b": "Association per doubling\n(percentage points)", "c": "Association per doubling\n(percentage points)",
               "d": "API-associated difference\n(percentage points)"}
    colors = {"quantity": "#4477AA", "api": "#AA3377"}
    fig, arr = plt.subplots(2, 2, figsize=(7.2, 5), sharex=True)
    axes = list(arr.flat)
    for axis, panel in zip(axes, ("a", "b", "c", "d"), strict=True):
        part = grid.loc[grid["panel"].eq(panel)].sort_values("ksc_z")
        if len(part) != 101:
            raise ValueError(f"KSC panel {panel} must contain 101 coordinates")
        _guard_coordinates(part, "ksc_z", "marginal_association", "marginal_ci_low", "marginal_ci_high")
        color = colors[str(part["resource"].iloc[0])]
        x = part["ksc_z"].to_numpy(float)
        axis.axhline(0, color="#777777", linewidth=.65, zorder=0)
        axis.axvline(0, color="#B0B0B0", linewidth=.6, linestyle="--", zorder=0)
        axis.fill_between(x, part["marginal_ci_low"].to_numpy(float), part["marginal_ci_high"].to_numpy(float), color=color, alpha=.18, linewidth=0)
        axis.plot(x, part["marginal_association"].to_numpy(float), color=color, linewidth=1.5)
        axis.set_title(titles[panel], loc="left", fontweight="bold")
        axis.set_ylabel(ylabels[panel])
        _label(axis, panel)
    for axis in arr[1, :]:
        axis.set_xlabel("Knowledge-space complexity (standardized)")
    fig.subplots_adjust(left=.13, right=.985, top=.94, bottom=.105, wspace=.34, hspace=.36)
    return _save(fig, axes, output_dir / "figures/ksc_marginal_associations")


def render_style_sha256(repo_root: Path) -> str:
    """Bind the recorded manual review to the actual drawing and export styles."""
    sections = [inspect.getsource(function) for function in (_style, _label, _save, draw_api, draw_ksc)]
    sections.extend([(HERE / "evolution_style.py").read_text(encoding="utf-8"),
                     (repo_root / "configs/figures/resource_evolution.json").read_text(encoding="utf-8")])
    return hashlib.sha256("\n".join(sections).encode("utf-8")).hexdigest()


def validate_figure_bundle(repo_root: Path, output_dir: Path, outputs: dict) -> dict:
    """Combine measured export QA with the recorded panel-by-panel review."""
    review = json.loads((repo_root / "configs/figures/qa_review.json").read_text(encoding="utf-8"))
    reviewed_panels = review["visual_review"]
    current_style = render_style_sha256(repo_root)
    reviewed_style = review.get("reviewed_render_style_sha256")
    stems = {"resource_trends": "combined_computational_resource_evolution",
             "hardware_api_interactions": "interaction_slopes_cumulative_citations",
             "ksc_marginal_associations": "ksc_marginal_associations"}
    figures = []
    for figure_id, stem in stems.items():
        measured = outputs[figure_id]
        current = output_dir / "figures" / f"{stem}.png"
        reference = repo_root / "results/reference/figures" / f"{stem}.png"
        with Image.open(current) as image:
            actual_pixels = np.asarray(image.convert("RGB"), dtype=np.int16)
        with Image.open(reference) as image:
            reference_pixels = np.asarray(image.convert("RGB"), dtype=np.int16)
        same_dimensions = actual_pixels.shape == reference_pixels.shape
        comparison = {"same_dimensions": same_dimensions,
                      "reference": f"results/reference/figures/{stem}.png"}
        if same_dimensions:
            difference = np.abs(actual_pixels - reference_pixels)
            comparison.update({"identical_pixels": bool(np.array_equal(actual_pixels, reference_pixels)),
                               "mean_absolute_channel_difference": float(difference.mean()),
                               "changed_pixel_fraction": float(np.any(difference != 0, axis=2).mean())})
        gates = {"alignment": measured["alignment"] == "PASS",
                 "font": measured["font_auditable"] and measured["font_below_minimum_count"] == 0,
                 "collision": measured["collision_auditable"] and measured["collision_failures"] == 0,
                 "export": all((output_dir / name).is_file() for name in measured["formats"])}
        # Current coordinates are checked numerically by the analysis verifier.
        # Pixel differences are recorded because font backends and antialiasing
        # can differ across platforms while preserving the scientific display.
        visual = {"passed": bool(reviewed_panels) and reviewed_style == current_style and all(gates.values()),
                  "render_style_sha256": current_style,
                  "reviewed_style_matches": reviewed_style == current_style,
                  "manual_review_record": "configs/figures/qa_review.json",
                  "manual_review_scope": "Original and locally regenerated panels with the retained drawing styles",
                  "manual_review_result": reviewed_panels,
                  "current_render": comparison}
        passed = all(gates.values()) and visual["passed"]
        figures.append({"figure_id": figure_id, "stem": stem, "passed": passed,
                        "alignment": {"passed": gates["alignment"], "verdict": measured["alignment"], "tolerance_pt": 1.5},
                        "font": {"passed": gates["font"], "auditable": measured["font_auditable"],
                                 "minimum_found_pt": measured["font_minimum_found_pt"], "minimum_required_pt": 5,
                                 "below_minimum_count": measured["font_below_minimum_count"], "text_run_count": measured["font_text_runs"]},
                        "collision": {"passed": gates["collision"], "auditable": measured["collision_auditable"],
                                      "failures": measured["collision_failures"], "warnings": measured["collision_warnings"]},
                        "visual_review": visual, "formats": measured["formats"]})
    report = {"schema_version": "figure_validation_v1", "passed": len(figures) == 3 and all(f["passed"] for f in figures),
              "figure_count": len(figures), "figures": figures}
    _write_json(output_dir / "figures/qa/figure_validation.json", report)
    if not report["passed"]:
        raise ValueError("Empirical figure bundle validation failed")
    return report


def run_figures(repo_root: Path, output_dir: Path, *, from_reference: bool = False) -> dict:
    repo_root, output_dir = Path(repo_root).resolve(), Path(output_dir).resolve()
    if output_dir == (repo_root / "results/reference").resolve():
        raise ValueError("Reference results are read-only")
    data_dir = output_dir / "figure_data"
    data_dir.mkdir(parents=True, exist_ok=True)
    config = json.loads((repo_root / "configs/figures/resource_evolution.json").read_text(encoding="utf-8"))
    reference = repo_root / "results/reference/figure_data"
    if from_reference:
        access = pd.read_csv(reference / "annual_hardware_api_configurations.csv")
        gpu = pd.read_csv(reference / "annual_gpu_hardware_configuration_quantiles.csv")
        summary = {"input_n": 107872, "hardware_n": 49090, "measurement_n": 34483, "performance_imputed_n": 3524,
                   "coordinate_origin": "explicit saved-coordinate redraw"}
        coordinate_dir = reference
    else:
        frame = pd.read_parquet(repo_root / "data/analysis_ready/resource_descriptive.parquet")
        access, gpu, summary = aggregate_evolution(frame, config)
        coordinate_dir = data_dir
    access.to_csv(data_dir / "annual_hardware_api_configurations.csv", index=False)
    gpu.to_csv(data_dir / "annual_gpu_hardware_configuration_quantiles.csv", index=False)
    predictions = pd.read_csv(coordinate_dir / "cumulative_citation_interaction_predictions.csv")
    contrasts = pd.read_csv(coordinate_dir / "cumulative_citation_interaction_contrasts.csv")
    grid = pd.read_csv(coordinate_dir / "marginal_figure_source.csv")
    fig, axes, inset = evolution_style.draw_evolution(access, gpu, config, config["component_configs"])
    outputs = {"resource_trends": _save(fig, axes, output_dir / "figures/combined_computational_resource_evolution", evolution=True, inset=inset),
               "hardware_api_interactions": draw_api(predictions, contrasts, output_dir),
               "ksc_marginal_associations": draw_ksc(grid, output_dir)}
    result = {"population": summary, "figures": outputs, "mode": "saved-coordinate redraw" if from_reference else "released-data and recomputed-model coordinates"}
    result["validation"] = validate_figure_bundle(repo_root, output_dir, outputs)
    _write_json(output_dir / "figures/qa/figure_summary.json", result)
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=HERE.parents[1])
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--from-reference", action="store_true")
    args = parser.parse_args()
    print(json.dumps(run_figures(args.repo_root, args.output_dir, from_reference=args.from_reference), indent=2))
